export const StotageKey = {
    SAVE_KEY_REQ_LOGIN: 'SAVE_KEY_REQ_LOGIN',
    SAVE_KEY_ACCOUNT_PW: 'SAVE_KEY_ACCOUNT_PW',
    SAVE_KEY_IS_REMEMBER: 'SAVE_KEY_IS_REMEMBER',
    SAVE_KEY_LOGIN_TYPE: 'SAVE_KEY_LOGIN_TYPE',
    SAVE_PLAYER_TOKEN: 'SAVE_PLAYER_TOKEN',
    SAVE_LANGUAGE: 'SAVE_LANGUAGE',
    SAVE_FROM_SUBGAME_ID: 'SAVE_FROM_SUBGAME_ID',
}